#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

constexpr auto DUMMY_PAYLOAD = ":";
constexpr auto MAX_ORDERED_PIZZAS_MULTIPLIER = 2;
constexpr auto KITCHEN_MONITORING_DEALY_IN_MILLISECONDS = 100;
constexpr auto KITCHEN_IDLE_TIME_LIMIT_IN_SECONDS = 3;

#endif //CONSTANTS_HPP
