#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define DEBUG 0

constexpr auto  DUMMY_PAYLOAD = ":";
constexpr auto MAX_ORDERED_PIZZAS_MULTIPLIER = 2;
constexpr auto INITIAL_INGREDIENT_COUNT = 5;
constexpr auto KITCHEN_MONITORING_DEALY_IN_MILLISECONDS = 100;
constexpr auto KITCHEN_IDLE_TIME_LIMIT_IN_SECONDS = 5;
constexpr auto RECEPTION_DEFAULT_IPC_ADDRESS = "reception";
constexpr auto RECEPTION_INITIAL_POOL_SIZE = 2;
constexpr auto POLLING_TIMEOUT_IN_SECONDS = 2;

#endif //CONSTANTS_HPP
